name: Deploy to AWS ECS

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download task definition 
      run: |
       aws ecs describe-task-definition --task-definition ecs-ci-cd-task-def --query taskDefinition > task-definition.json
          
    - name: Update ECS Task Definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: fastapi
        image: ${{ secrets.DOCKER_USERNAME }}/fastapideploy:${{ github.event.inputs.imageTag }}

    - name: Deploy to ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        cluster: ${{ secrets.ECS_CLUSTER_NAME }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
